In [1]:
# Example of SVD and demonstrations using numpy and scipy libraries
import scipy as sp
import numpy as np
from scipy import linalg as la

A = np.array([[4.0,3.0], [2.0,2.0], [-1.0,-3.0], [-5.0,-2.0]])
U, S, Vt = la.svd(A, full_matrices=False)
print(U)

[[-0.61215255 -0.05228813]
 [-0.34162337 -0.2025832 ]
 [ 0.31300005  0.80704816]
 [ 0.64077586 -0.55217683]]


In [2]:
print(S)

[8.16552039 2.30743942]


In [3]:
print(Vt)

[[-0.81424526 -0.58052102]
 [ 0.58052102 -0.81424526]]


In [8]:
x = np.array([0.243,0.97])
print(x) # Original
x = x / la.norm(x)
print(x) # Should now be a unit vector... ||x|| = 1

[0.243 0.97 ]
[0.2430062  0.97002474]


In [9]:
xi = Vt.dot(x)
print(xi)

[-0.7609864  -0.64876784]


In [10]:
print(la.norm(xi)) # Norm hasnt changed

1.0


In [12]:
newS = la.diagsvd(S,2,2)
eta = newS.dot(xi)
print(eta)

[-6.21384993 -1.49699248]


In [13]:
print(la.norm(eta)) # The stretch along the axis does change the norm of the vector

6.391628704703712


In [14]:
y = U.dot(eta)
print(y) # Equal to Ax

[ 3.88209899  2.42606187 -3.1530804  -3.15508046]


In [15]:
print(A.dot(x)) # Equal to y

[ 3.88209899  2.42606187 -3.1530804  -3.15508046]
